service: product-service

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  httpApi:
    cors: true
  environment:
    DYNAMODB_PRODUCTS_DB: ${env:DYNAMODB_PRODUCTS_DB}
    DYNAMODB_STOCKS_DB: ${env:DYNAMODB_STOCKS_DB}

plugins:
  - serverless-webpack

functions:
  getProductsList:
    handler: src/getProductsList.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
  getProductsById:
    handler: src/getProductsById.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get
  createProduct:
    handler: src/createProduct.createProduct
    events:
      - httpApi:
          path: /products
          method: post
