service: product-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  httpApi:
    cors: true

plugins:
  - serverless-webpack

functions:
  getProductsList:
    handler: src/getProductsList.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
  getProductsById:
    handler: src/getProductsById.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get
