swagger: "2.0"
info:
  description: "Programming Book Shop BE endpoints"
  version: "1.0.0"
  title: "Programming Book Shop Swagger"
tags:
- name: "product-service"
schemes:
- "https"
paths:
  /products:
    get:
      tags:
      - "product-service"
      description: "Get a list of products"
      produces: 
      - "application/json"
      responses:
        "200":
          description: "Return an array with products"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ProductResponse"
        "500":
          description: "Something went wrong during getting product list"
    post:
      tags:
      - "product-service"
      summary: "Create product"
      description: "Create a new product"
      parameters:
      - name: "create_product_body"
        in: "body"
        description: "Create a new product"
        schema:
          $ref: '#/definitions/CreateProductBody'
      responses:
        "201":
          description: "Return a product"
          schema:
            $ref: "#/definitions/ProductResponse"
        "400":
          description: "Data for creating new product is not defined OR Data for creating new product is not valid"
        "500":
          description: "Something went wrong during the creation of new product"
  /products/{productId}:
    get:
      tags:
      - "product-service"
      summary: "Get one product"
      description: "Get one products by id"
      produces:
      - "application/json"
      parameters:
      - name: "productId"
        in: "path"
        description: "Product id in DB"
        required: true
        type: "string"
        format: "uuid"
      responses:
        "200":
          description: "Return a product"
          schema:
            $ref: "#/definitions/ProductResponse"
        "400":
          description: "Product id is not defined OR Stock not found"
        "404":
          description: "Product not found!"
        "500":
          description: "Something went wrong during getting product by id"
definitions:
  ProductResponse:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      title:
        type: "string"
      description:
        type: "string"
      count:
        type: "number"
        format: "integer64"
      price:
        type: "number"
        format: "integer64"
  CreateProductBody:
    type: "object"
    properties:
      title:
        type: "string"
      description:
        type: "string"
      count:
        type: "number"
        format: "integer64"
      price:
        type: "number"
        format: "integer64"