service: import-service

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  httpApi:
    cors: true
  environment:
    BUCKET_NAME: ${env:BUCKET_NAME}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:ListBucket
          Resource:
            - arn:aws:s3:::${env:BUCKET_NAME}
        - Effect: Allow
          Action:
            - s3:*
          Resource:
            - arn:aws:s3:::${env:BUCKET_NAME}/*

plugins:
  - serverless-webpack

functions:
  importProductsFile:
    handler: src/importProductsFile.importProductsFile
    events:
      - httpApi:
          method: get
          path: /import
  # importProductsFile:
  #   handler: src/importProductsFile.importProductsFile
  #   events:
  #     - http:
  #         method: get
  #         path: /import
  #         cors: true
  #         request:
  #           parameters:
  #             querystrings:
  #               name: true
  importFileParser:
    handler: src/importFileParser.importFileParser
    events:
      - s3:
          bucket: ${env:BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true