service: import-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource:
            - 'arn:aws:s3:::import-service-rss-nodejs-in-aws-course'
        - Effect: Allow
          Action:
            - 's3:*'
          Resource:
            - 'arn:aws:s3:::import-service-rss-nodejs-in-aws-course/*'

plugins:
  - serverless-webpack

functions:
  importProductsFile:
    handler: src/importProductsFile.importProductsFile
    events:
      - http:
          method: get
          path: /import
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: src/importFileParser.importFileParser
    events:
      - s3:
          bucket: import-service-rss-nodejs-in-aws-course
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true